### ISSUE TITLE
Lines matching up on dung

### ISSUE THREAD

**Issue by amberfoam** [fo-am/iCrapAppPro#12]
The comment was 'lines matching up on dung' and 'lines moving so bar can see dung photo'... hopefully this makes sense to you!

**Comment by aidanw** [comment]
'lines moving so bar can see dung photo' is the same as #13 

 'lines matching up on dung' is table formatting for nutrients on the spread event screen.

**Comment by aidanw** [comment]
'lines matching up on dung' is handled in #17
