### ISSUE TITLE
Crops - spent mushroom is duplicated

### ISSUE THREAD

**Issue by amberfoam** [fo-am/iCrapAppPro#4]

**Comment by aidanw** [comment]
Fixed in this horror merge/commit

https://github.com/fo-am/iCrapAppPro/commit/a414607104937f086bdd6fa736217d6e16dc7603

It was a copy paste error in generating the translation file (src/assets/Strings.ts ) 
I cannot think of an automated way of looking for other 'snafus' but I will look by eye!

**Comment by aidanw** [comment]
I cannot see any more, closing this and can open more if they raise their heads!
